version: '3'
services:
  database:
    image: 'postgres:latest'
    container_name: gelarm
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./gelarm_tables.ddl:/gelarm_tables.ddl